// SPDX-FileCopyrightText: 2024 Piras314 <p1r4s@proton.me>
// SPDX-FileCopyrightText: 2024 metalgearsloth <31366439+metalgearsloth@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 SX_7 <sn1.test.preria.2002@gmail.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using System.Numerics; // Pirate: multiz
using System.Text;
using Content.Shared._Pirate.ZLevels.Core.Components; // Pirate: multiz
using Content.Shared.Shuttles.BUIStates;
using Content.Shared.Shuttles.Systems;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface; // Pirate: multiz
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Shuttles.UI;

[GenerateTypedNameReferences]
public sealed partial class DockingScreen : BoxContainer
{
    [Dependency] private readonly IEntityManager _entManager = default!;
    private readonly SharedShuttleSystem _shuttles;

    /// <summary>
    /// Stored by GridID then by docks
    /// </summary>
    public Dictionary<NetEntity, List<DockingPortState>> Docks = new();

    /// <summary>
    /// Store the dock buttons for the side buttons.
    /// </summary>
    private readonly Dictionary<NetEntity, Button> _ourDockButtons = new();

    #region Pirate: multiz
    /// <summary>
    /// The grid the shuttle console is physically mounted on. Used as the root for z-network
    /// peer discovery and as the fallback when the selected layer becomes invalid.
    /// </summary>
    private EntityUid? _consoleShuttle;

    /// <summary>
    /// The z-layer (grid) whose docks are currently shown in the side list and rendered by the
    /// dock control. Preserved across state updates so the user's tab selection doesn't reset
    /// every time the server pushes a new state.
    /// </summary>
    private EntityUid? _selectedLayer;
    #endregion

    public event Action<NetEntity, NetEntity>? DockRequest;
    public event Action<NetEntity>? UndockRequest;

    public DockingScreen()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _shuttles = _entManager.System<SharedShuttleSystem>();

        DockingControl.OnViewDock += OnView;
        DockingControl.DockRequest += (entity, netEntity) =>
        {
            DockRequest?.Invoke(entity, netEntity);
        };
        DockingControl.UndockRequest += entity =>
        {
            UndockRequest?.Invoke(entity);
        };
    }

    private void OnView(NetEntity obj)
    {
        if (_ourDockButtons.TryGetValue(obj, out var viewed))
        {
            viewed.Pressed = true;
        }
    }

    public void UpdateState(EntityUid? shuttle, DockingInterfaceState state)
    {
        Docks = state.Docks;
        DockingControl.DockState = state;

        #region Pirate: multiz
        // If the console moves to a different shuttle (or first ever update) drop the selection;
        // otherwise keep it so the user doesn't get yanked back to deck 0 each server push.
        if (_consoleShuttle != shuttle)
        {
            _consoleShuttle = shuttle;
            _selectedLayer = shuttle;
        }

        if (!IsLayerInNetwork(_selectedLayer, _consoleShuttle))
            _selectedLayer = _consoleShuttle;

        RebuildLayerSelector();

        DockingControl.GridEntity = _selectedLayer;
        BuildDocks(_selectedLayer);
        #endregion
    }

    #region Pirate: multiz
    private bool IsLayerInNetwork(EntityUid? layer, EntityUid? root)
    {
        if (layer is null || root is null || !_entManager.EntityExists(layer))
            return false;

        if (layer == root)
            return true;

        if (!_entManager.TryGetComponent(root.Value, out CEZLinkedGridComponent? linked))
            return false;

        foreach (var (_, peer) in linked.PeerGrids)
        {
            if (peer == layer.Value)
                return true;
        }

        return false;
    }

    private void RebuildLayerSelector()
    {
        LayerSelectorRow.RemoveAllChildren();

        if (_consoleShuttle is null
            || !_entManager.TryGetComponent(_consoleShuttle.Value, out CEZLinkedGridComponent? linked)
            || linked.PeerGrids.Count == 0)
        {
            LayerSelectorRow.Visible = false;
            return;
        }

        // Build a depth-sorted list including the console's own grid.
        var levels = new SortedDictionary<int, EntityUid>(linked.PeerGrids)
        {
            [linked.Depth] = _consoleShuttle.Value,
        };

        LayerSelectorRow.Visible = true;

        // Match the camera monitor / gunnery console "Z: 0 1 2" inline layout.
        LayerSelectorRow.AddChild(new Label
        {
            Text = "Z:",
            VerticalAlignment = VAlignment.Center,
            Margin = new Thickness(0f, 0f, 4f, 0f),
        });

        var group = new ButtonGroup();
        foreach (var (depth, gridUid) in levels)
        {
            var isSelected = _selectedLayer == gridUid;
            var button = new Button
            {
                Text = depth.ToString(),
                ToggleMode = true,
                Group = group,
                Pressed = isSelected,
                Margin = new Thickness(2f, 0f),
                MinSize = new Vector2(28f, 0f),
            };

            var capturedGrid = gridUid;
            button.OnPressed += _ =>
            {
                if (_selectedLayer == capturedGrid)
                    return;

                _selectedLayer = capturedGrid;
                DockingControl.GridEntity = _selectedLayer;
                BuildDocks(_selectedLayer);
            };

            LayerSelectorRow.AddChild(button);
        }
    }
    #endregion

    private void BuildDocks(EntityUid? shuttle)
    {
        DockingControl.BuildDocks(shuttle);
        var currentDock = DockingControl.ViewedDock;
        // DockedWith.DisposeAllChildren();
        DockPorts.DisposeAllChildren();
        _ourDockButtons.Clear();

        if (shuttle == null)
        {
            DockingControl.SetViewedDock(null);
            return;
        }

        var shuttleNent = _entManager.GetNetEntity(shuttle.Value);

        if (!Docks.TryGetValue(shuttleNent, out var shuttleDocks) || shuttleDocks.Count <= 0)
        {
            // Pirate: multiz - layer has no docks; drop the carried-over viewed dock so the
            // radar isn't still rendering a port from a previously-selected layer.
            DockingControl.SetViewedDock(null);
            return;
        }

        var dockText = new StringBuilder();
        var buttonGroup = new ButtonGroup();
        var idx = 0;
        var selected = false;

        // Build the dock buttons for our docks.
        foreach (var dock in shuttleDocks)
        {
            idx++;
            dockText.Clear();
            dockText.Append(dock.Name);

            var button = new Button()
            {
                Text = dockText.ToString(),
                ToggleMode = true,
                Group = buttonGroup,
                Margin = new Thickness(0f, 3f),
            };

            button.OnMouseEntered += args =>
            {
                DockingControl.HighlightedDock = dock.Entity;
            };

            button.OnMouseExited += args =>
            {
                DockingControl.HighlightedDock = null;
            };

            button.Label.Margin = new Thickness(3f);

            if (currentDock == dock.Entity)
            {
                selected = true;
                button.Pressed = true;
            }

            button.OnPressed += args =>
            {
                OnDockPress(dock);
            };

            _ourDockButtons[dock.Entity] = button;
            DockPorts.AddChild(button);
        }

        // Button group needs one selected so just show the first one.
        if (!selected)
        {
            var buttonOne = shuttleDocks[0];
            OnDockPress(buttonOne);
        }

        var shuttleContainers = new Dictionary<NetEntity, DockObject>();

        foreach (var dock in shuttleDocks.OrderBy(x => x.GridDockedWith))
        {
            if (dock.GridDockedWith == null)
                continue;

            DockObject? dockContainer;

            if (!shuttleContainers.TryGetValue(dock.GridDockedWith.Value, out dockContainer))
            {
                dockContainer = new DockObject();
                shuttleContainers[dock.GridDockedWith.Value] = dockContainer;
                var dockGrid = _entManager.GetEntity(dock.GridDockedWith);
                string? iffLabel = null;

                if (_entManager.EntityExists(dockGrid))
                {
                    iffLabel = _shuttles.GetIFFLabel(dockGrid.Value);
                }

                iffLabel ??= Loc.GetString("shuttle-console-unknown");
                dockContainer.SetName(iffLabel);
                // DockedWith.AddChild(dockContainer);
            }

            dockContainer.AddDock(dock, DockingControl);
        }
    }

    private void OnDockPress(DockingPortState state)
    {
        DockingControl.SetViewedDock(state);
    }
}