using Content.Shared._Pirate.MassDriver;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Pirate.MassDriver.UI;

[GenerateTypedNameReferences]
public sealed partial class MassDriverConsoleMenu : DefaultWindow
{
    public event Action? OnLaunchButtonPressed;
    public event Action<MassDriverMode>? OnModeButtonPressed;
    public event Action<float>? OnThrowSpeed;
    public event Action<float>? OnThrowDistance;

    public MassDriverConsoleMenu()
    {
        RobustXamlLoader.Load(this);

        LaunchButton.OnPressed += _ => OnLaunchButtonPressed?.Invoke();

        AutoModeButton.OnPressed += _ =>
        {
            AutoModeButton.Disabled = true;
            ManualModeButton.Disabled = false;
            LaunchButton.Disabled = true;
            OnModeButtonPressed?.Invoke(MassDriverMode.Auto);
        };

        ManualModeButton.OnPressed += _ =>
        {
            AutoModeButton.Disabled = false;
            ManualModeButton.Disabled = true;
            LaunchButton.Disabled = false;
            OnModeButtonPressed?.Invoke(MassDriverMode.Manual);
        };

        ThrowDistanceSlider.OnValueChanged += _ =>
        {
            var throwDistance = Normalize(ThrowDistanceSlider.Value);
            OnThrowDistance?.Invoke(throwDistance);
            ThrowDistanceCurrentValue.Text = FormatDistance(throwDistance);
        };

        ThrowSpeedSlider.OnValueChanged += _ =>
        {
            var throwSpeed = Normalize(ThrowSpeedSlider.Value);
            OnThrowSpeed?.Invoke(throwSpeed);
            ThrowSpeedCurrentValue.Text = FormatSpeed(throwSpeed);
        };
    }

    public void UpdateState(MassDriverComponentState state)
    {
        if (state.Console != null)
        {
            DisabledPanel.Visible = false;
            DisabledPanel.MouseFilter = MouseFilterMode.Ignore;
        }
        else
        {
            DisabledPanel.Visible = true;
            DisabledPanel.MouseFilter = MouseFilterMode.Stop;

            if (DisabledLabel.GetMessage() is null)
            {
                var text = new FormattedMessage();
                text.AddMarkupOrThrow(Loc.GetString("mass-driver-ui-link"));
                DisabledLabel.SetMessage(text);
            }
        }

        if (state.CurrentMassDriverMode == MassDriverMode.Auto)
        {
            AutoModeButton.Disabled = true;
            ManualModeButton.Disabled = false;
            LaunchButton.Disabled = true;
        }
        else
        {
            ManualModeButton.Disabled = true;
            AutoModeButton.Disabled = false;
            LaunchButton.Disabled = false;
        }

        ThrowDistanceCurrentValue.Text = FormatDistance(state.CurrentThrowDistance);
        ThrowSpeedCurrentValue.Text = FormatSpeed(state.CurrentThrowSpeed);

        ThrowDistanceMaxValue.Text = state.MaxThrowDistance.ToString();
        ThrowDistanceMinValue.Text = state.MinThrowDistance.ToString();
        ThrowSpeedMaxValue.Text = state.MaxThrowSpeed.ToString();
        ThrowSpeedMinValue.Text = state.MinThrowSpeed.ToString();

        ThrowDistanceSlider.MaxValue = state.MaxThrowDistance;
        ThrowDistanceSlider.MinValue = state.MinThrowDistance;
        ThrowDistanceSlider.Value = state.CurrentThrowDistance;

        ThrowSpeedSlider.MaxValue = state.MaxThrowSpeed;
        ThrowSpeedSlider.MinValue = state.MinThrowSpeed;
        ThrowSpeedSlider.Value = state.CurrentThrowSpeed;
    }

    private static float Normalize(float value, int decimals = 1)
    {
        return (float) Math.Round(value, decimals, MidpointRounding.AwayFromZero);
    }

    private static string FormatDistance(float value)
    {
        return $"{value} {Loc.GetString("mass-driver-ui-units-distance")}";
    }

    private static string FormatSpeed(float value)
    {
        return $"{value} {Loc.GetString("mass-driver-ui-units-speed")}";
    }
}
