# ==========================================
# SCP PLAYTIME TRACKERS
# ==========================================
- type: playTimeTracker
  id: JobSCPClassD
- type: playTimeTracker
  id: JobSCPSiteDirector
- type: playTimeTracker
  id: JobSCPSiteManager
- type: playTimeTracker
  id: JobSCPCommunicationsOfficer
- type: playTimeTracker
  id: JobSCPISDDetective
- type: playTimeTracker
  id: JobSCPEthicsCommittee
- type: playTimeTracker
  id: JobSCPGOCRepresentative
- type: playTimeTracker
  id: JobSCPCommsTechnician
- type: playTimeTracker
  id: JobSCPEngineeringDirector
- type: playTimeTracker
  id: JobSCPAsstEngDirector
- type: playTimeTracker
  id: JobSCPContainmentEngineer
- type: playTimeTracker
  id: JobSCPSeniorEngineer
- type: playTimeTracker
  id: JobSCPEngineer
- type: playTimeTracker
  id: JobSCPJuniorEngineer
- type: playTimeTracker
  id: JobSCPMedicalDirector
- type: playTimeTracker
  id: JobSCPAsstMedDirector
- type: playTimeTracker
  id: JobSCPSurgeon
- type: playTimeTracker
  id: JobSCPChemist
- type: playTimeTracker
  id: JobSCPPsychiatrist
- type: playTimeTracker
  id: JobSCPMedicalDoctor
- type: playTimeTracker
  id: JobSCPEMT
- type: playTimeTracker
  id: JobSCPMedicalIntern
- type: playTimeTracker
  id: JobSCPLogisticsOfficer
- type: playTimeTracker
  id: JobSCPLogisticsSpecialist
- type: playTimeTracker
  id: JobSCPOfficeWorker
- type: playTimeTracker
  id: JobSCPBartender
- type: playTimeTracker
  id: JobSCPChaplain
- type: playTimeTracker
  id: JobSCPResearchDirector
- type: playTimeTracker
  id: JobSCPSeniorResearcher
- type: playTimeTracker
  id: JobSCPSeniorRobotics
- type: playTimeTracker
  id: JobSCPResearcher
- type: playTimeTracker
  id: JobSCPRoboticsTechnician
- type: playTimeTracker
  id: JobSCPResearcherAssociate
- type: playTimeTracker
  id: JobSCPJuniorRobotics
- type: playTimeTracker
  id: JobSCPGuardCommander
- type: playTimeTracker
  id: JobSCPLCZJuniorLt
- type: playTimeTracker
  id: JobSCPHCZSeniorLt
- type: playTimeTracker
  id: JobSCPEZSupervisor
- type: playTimeTracker
  id: JobSCPRAISAAgent
- type: playTimeTracker
  id: JobSCPLCZSergeant
- type: playTimeTracker
  id: JobSCPHCZSergeant
- type: playTimeTracker
  id: JobSCPEZSeniorAgent
- type: playTimeTracker
  id: JobSCPLCZGuard
- type: playTimeTracker
  id: JobSCPHCZGuard
- type: playTimeTracker
  id: JobSCPEZAgent
- type: playTimeTracker
  id: JobSCPLCZCadet
- type: playTimeTracker
  id: JobSCPHCZPrivate
- type: playTimeTracker
  id: JobSCPEZProbAgent
- type: playTimeTracker
  id: JobSCPAIC
- type: playTimeTracker
  id: JobSCPRobot
- type: playTimeTracker
  id: JobSCPO5Council
- type: playTimeTracker
  id: JobSCPMTFE11Commander
- type: playTimeTracker
  id: JobSCPMTFE11Lieutenant
- type: playTimeTracker
  id: JobSCPMTFE11Sergeant
- type: playTimeTracker
  id: JobSCPMTFE11Agent
- type: playTimeTracker
  id: JobSCPMTFNU7Commander
- type: playTimeTracker
  id: JobSCPMTFNU7Lieutenant
- type: playTimeTracker
  id: JobSCPMTFNU7Agent