using System.Linq;
using Content.Client.Administration.UI.CustomControls;
using Content.Shared._Pirate.CartridgeLoader.Cartridges;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Pirate.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class StockTradingUiFragment : BoxContainer
{
    private readonly Dictionary<int, CompanyEntry> _companyEntries = new();

    public event Action<int, int>? OnBuyButtonPressed;
    public event Action<int, int>? OnSellButtonPressed;

    public static readonly Color PositiveColor = Color.FromHex("#00ff00");
    public static readonly Color NegativeColor = Color.FromHex("#ff0000");
    public static readonly Color NeutralColor = Color.FromHex("#ffffff");
    public static readonly Color BackgroundColor = Color.FromHex("#25252a");
    public static readonly Color PriceBackgroundColor = Color.FromHex("#1a1a1a");
    public static readonly Color BorderColor = Color.FromHex("#404040");

    public StockTradingUiFragment()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(StockTradingUiState state)
    {
        NoEntries.Visible = state.Entries.Count == 0;
        Balance.Text = Loc.GetString("stock-trading-balance", ("balance", state.Balance));

        foreach (var entry in _companyEntries.Values)
        {
            entry.Container.RemoveAllChildren();
        }

        _companyEntries.Clear();
        Entries.RemoveAllChildren();

        for (var i = 0; i < state.Entries.Count; i++)
        {
            var company = state.Entries[i];
            var entry = new CompanyEntry(i, company.LocalizedDisplayName, OnBuyButtonPressed, OnSellButtonPressed);
            _companyEntries[i] = entry;
            Entries.AddChild(entry.Container);

            var ownedStocks = state.OwnedStocks.GetValueOrDefault(i, 0);
            entry.Update(company, ownedStocks);
        }
    }

    private sealed class CompanyEntry
    {
        public readonly BoxContainer Container;
        private readonly Label _nameLabel;
        private readonly Label _priceLabel;
        private readonly Label _changeLabel;
        private readonly Button _sellButton;
        private readonly Label _sharesLabel;
        private readonly LineEdit _amountEdit;
        private readonly PriceHistoryTable _priceHistory;

        public CompanyEntry(
            int companyIndex,
            string displayName,
            Action<int, int>? onBuyPressed,
            Action<int, int>? onSellPressed)
        {
            Container = new BoxContainer
            {
                Orientation = LayoutOrientation.Vertical,
                HorizontalExpand = true,
                Margin = new Thickness(0, 0, 0, 2),
            };

            var companyPanel = new PanelContainer();
            var mainContent = new BoxContainer
            {
                Orientation = LayoutOrientation.Vertical,
                HorizontalExpand = true,
                Margin = new Thickness(8),
            };

            var topRow = new BoxContainer
            {
                Orientation = LayoutOrientation.Horizontal,
                HorizontalExpand = true,
            };

            _nameLabel = new Label
            {
                HorizontalExpand = true,
                Text = displayName,
            };

            var pricePanel = new PanelContainer
            {
                HorizontalAlignment = HAlignment.Right,
            };

            var priceStyleBox = new StyleBoxFlat
            {
                BackgroundColor = BackgroundColor,
                ContentMarginLeftOverride = 8,
                ContentMarginRightOverride = 8,
                ContentMarginTopOverride = 4,
                ContentMarginBottomOverride = 4,
                BorderColor = BorderColor,
                BorderThickness = new Thickness(1),
            };

            pricePanel.PanelOverride = priceStyleBox;

            var priceContainer = new BoxContainer
            {
                Orientation = LayoutOrientation.Horizontal,
            };

            _priceLabel = new Label();
            _changeLabel = new Label
            {
                HorizontalAlignment = HAlignment.Right,
                Modulate = NeutralColor,
                Margin = new Thickness(15, 0, 0, 0),
            };

            priceContainer.AddChild(_priceLabel);
            priceContainer.AddChild(_changeLabel);
            pricePanel.AddChild(priceContainer);

            topRow.AddChild(_nameLabel);
            topRow.AddChild(pricePanel);
            mainContent.AddChild(topRow);

            _priceHistory = new PriceHistoryTable();
            mainContent.AddChild(_priceHistory);

            var bottomRow = new BoxContainer
            {
                Orientation = LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                Margin = new Thickness(0, 5, 0, 0),
            };

            _sharesLabel = new Label
            {
                Text = Loc.GetString("stock-trading-owned-shares"),
                MinWidth = 100,
            };

            _amountEdit = new LineEdit
            {
                PlaceHolder = Loc.GetString("stock-trading-amount-placeholder"),
                HorizontalExpand = true,
                MinWidth = 80,
            };

            var buttonContainer = new BoxContainer
            {
                Orientation = LayoutOrientation.Horizontal,
                HorizontalAlignment = HAlignment.Right,
                MinWidth = 140,
            };

            var buyButton = new Button
            {
                Text = Loc.GetString("stock-trading-buy-button"),
                MinWidth = 65,
                Margin = new Thickness(3, 0, 3, 0),
            };

            _sellButton = new Button
            {
                Text = Loc.GetString("stock-trading-sell-button"),
                MinWidth = 65,
            };

            buttonContainer.AddChild(buyButton);
            buttonContainer.AddChild(_sellButton);

            bottomRow.AddChild(_sharesLabel);
            bottomRow.AddChild(_amountEdit);
            bottomRow.AddChild(buttonContainer);
            mainContent.AddChild(bottomRow);

            companyPanel.AddChild(mainContent);
            Container.AddChild(companyPanel);
            Container.AddChild(new HSeparator { Margin = new Thickness(5, 3, 5, 5) });

            buyButton.OnPressed += _ =>
            {
                if (int.TryParse(_amountEdit.Text, out var amount) && amount > 0)
                    onBuyPressed?.Invoke(companyIndex, amount);
            };

            _sellButton.OnPressed += _ =>
            {
                if (int.TryParse(_amountEdit.Text, out var amount) && amount > 0)
                    onSellPressed?.Invoke(companyIndex, amount);
            };

            _amountEdit.OnTextChanged += args =>
            {
                var newText = string.Concat(args.Text.Where(char.IsDigit));
                if (newText != args.Text)
                    _amountEdit.Text = newText;
            };
        }

        public void Update(StockCompany company, int ownedStocks)
        {
            _nameLabel.Text = company.LocalizedDisplayName;
            _priceLabel.Text = $"${company.CurrentPrice:F2}";
            _sharesLabel.Text = Loc.GetString("stock-trading-owned-shares", ("shares", ownedStocks));

            var priceHistory = company.PriceHistory is { Count: > 0 }
                ? company.PriceHistory
                : Enumerable.Repeat(company.CurrentPrice > 0 ? company.CurrentPrice : company.BasePrice, 5).ToList();

            var priceChange = 0f;
            if (priceHistory.Count > 0)
            {
                var previousPrice = priceHistory[^1];
                priceChange = (company.CurrentPrice - previousPrice) / previousPrice * 100;
            }

            _changeLabel.Text = $"{(priceChange >= 0 ? "+" : "")}{priceChange:F2}%";
            _changeLabel.Modulate = priceChange switch
            {
                > 0 => PositiveColor,
                < 0 => NegativeColor,
                _ => NeutralColor,
            };

            _priceHistory.Update(priceHistory);

            _sellButton.Disabled = ownedStocks <= 0;
        }
    }
}
