using Content.Shared._Pirate.ZLevels.Elevators;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Pirate.ZLevels.Elevators;

[GenerateTypedNameReferences]
public sealed partial class CEElevatorWindow : DefaultWindow
{
    public Action<int>? OnFloorSelected;

    public CEElevatorWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(BoundUserInterfaceState state)
    {
        if (state is not CEElevatorBuiState cast)
            return;

        FloorList.RemoveAllChildren();

        if (!cast.Operational)
        {
            StatusLabel.Text = "Out of service";
            return;
        }

        StatusLabel.Text = cast.Moving ? "Travelling..." : "Select a floor";

        foreach (var floor in cast.Floors)
        {
            var isCurrent = floor.Depth == cast.CurrentDepth;
            var button = new Button
            {
                Text = isCurrent ? $"{floor.Name}  (here)" : floor.Name,
                Disabled = cast.Moving || isCurrent,
                Margin = new Robust.Shared.Maths.Thickness(0, 0, 0, 2),
                HorizontalExpand = true,
            };

            var depth = floor.Depth;
            button.OnPressed += _ => OnFloorSelected?.Invoke(depth);
            FloorList.AddChild(button);
        }
    }
}
