// SPDX-FileCopyrightText: 2022 Flipp Syder <76629141+vulppine@users.noreply.github.com>
// SPDX-FileCopyrightText: 2022 metalgearsloth <comedian_vs_clown@hotmail.com>
// SPDX-FileCopyrightText: 2023 Artjom <artjombebenin@gmail.com>
// SPDX-FileCopyrightText: 2023 Artur <thearturzh@gmail.com>
// SPDX-FileCopyrightText: 2023 faint <46868845+ficcialfaint@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 nikthechampiongr <32041239+nikthechampiongr@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Shared.StationRecords;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.StationRecords;

[GenerateTypedNameReferences]
public sealed partial class GeneralStationRecordConsoleWindow : DefaultWindow
{
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

    public Action<uint?>? OnKeySelected;
    public Action<StationRecordFilterType, string>? OnFiltersChanged;
    #region Pirate: general/security record decoupling
    public Action<uint>? OnDeleteRecord;
    public Action<string>? OnCreateRecord;
    public Action<string, string, string, int, Robust.Shared.Enums.Gender>? OnIdentityInfoChanged;
    public Action<string, string>? OnForensicsInfoChanged;
    #endregion

    private bool _isPopulating;
    private StationRecordFilterType _currentFilterType;
    private uint? _selectedKey;
    private uint _maxLength;
    private bool _canManageRecords;
    private bool _deleteConfirmationPending;
    private uint? _deleteConfirmationKey;

    public GeneralStationRecordConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _currentFilterType = StationRecordFilterType.Name;

        foreach (var item in Enum.GetValues<StationRecordFilterType>())
        {
            StationRecordsFilterType.AddItem(GetTypeFilterLocals(item), (int) item);
        }

        RecordListing.OnItemSelected += args =>
        {
            if (_isPopulating || RecordListing[args.ItemIndex].Metadata is not uint cast)
                return;

            OnKeySelected?.Invoke(cast);
        };

        RecordListing.OnItemDeselected += _ =>
        {
            if (_isPopulating)
                return;

            OnKeySelected?.Invoke(null);
        };

        StationRecordsFilterType.OnItemSelected += eventArgs =>
        {
            var type = (StationRecordFilterType) eventArgs.Id;

            if (_currentFilterType != type)
            {
                _currentFilterType = type;
                FilterListingOfRecords(StationRecordsFiltersValue.Text);
            }
        };

        StationRecordsFiltersValue.OnTextEntered += args => FilterListingOfRecords(args.Text);
        StationRecordsFiltersValue.OnTextChanged += _ =>
        {
            ResetDeleteConfirmation();
            UpdateRecordActionButtons();
        };

        AddRecordButton.OnPressed += _ => CreateRecordFromSearch();
        DeleteRecordButton.OnPressed += _ =>
        {
            if (_selectedKey == null)
                return;

            if (_deleteConfirmationPending && _deleteConfirmationKey == _selectedKey)
            {
                ResetDeleteConfirmation();
                OnDeleteRecord?.Invoke(_selectedKey.Value);
                return;
            }

            _deleteConfirmationPending = true;
            _deleteConfirmationKey = _selectedKey;
            UpdateRecordActionButtons();
        };

        UpdateRecordActionButtons();
    }

    public void UpdateState(GeneralStationRecordConsoleState state)
    {
        var previousSelectedKey = _selectedKey;
        _maxLength = state.MaxStringLength;
        _canManageRecords = state.CanDeleteEntries;

        if (state.Filter != null)
        {
            if (state.Filter.Type != _currentFilterType)
                _currentFilterType = state.Filter.Type;

            if (state.Filter.Value != StationRecordsFiltersValue.Text)
                StationRecordsFiltersValue.Text = state.Filter.Value;
        }

        _selectedKey = state.SelectedKey;
        if (previousSelectedKey != _selectedKey)
            ResetDeleteConfirmation();

        StationRecordsFilterType.SelectId((int) _currentFilterType);

        if (state.RecordListing == null)
        {
            RecordListingStatus.Visible = true;
            RecordListing.Visible = false;
            RecordListingStatus.Text = Loc.GetString("general-station-record-console-empty-state");
            RecordContainer.Visible = false;
            RecordContainerStatus.Visible = false;
            UpdateRecordActionButtons();
            return;
        }

        RecordListingStatus.Visible = false;
        RecordListing.Visible = true;
        RecordContainer.Visible = true;
        PopulateRecordListing(state.RecordListing, state.SelectedKey);
        UpdateRecordActionButtons();

        RecordContainerStatus.Visible = state.Record == null;

        if (state.Record != null)
        {
            RecordContainerStatus.Visible = state.SelectedKey == null;
            RecordContainerStatus.Text = state.SelectedKey == null
                ? Loc.GetString("general-station-record-console-no-record-found")
                : Loc.GetString("general-station-record-console-select-record-info");
            PopulateRecordContainer(state.Record);
        }
        else
        {
            RecordContainer.RemoveAllChildren();
        }
    }

    private void PopulateRecordListing(Dictionary<uint, string> listing, uint? selected)
    {
        RecordListing.Clear();
        RecordListing.ClearSelected();

        _isPopulating = true;
        foreach (var (key, name) in listing)
        {
            var item = RecordListing.AddItem(name);
            item.Metadata = key;
            item.Selected = key == selected;
        }

        _isPopulating = false;
        RecordListing.SortItemsByText();
    }

    private void PopulateRecordContainer(GeneralStationRecord record)
    {
        RecordContainer.RemoveAllChildren();
        var newRecord = new GeneralRecord(record, _maxLength, _prototypeManager);
        newRecord.OnIdentityInfoChanged += (species, nationality, employer, age, gender) =>
            OnIdentityInfoChanged?.Invoke(species, nationality, employer, age, gender);
        newRecord.OnForensicsInfoChanged += (fingerprint, dna) =>
            OnForensicsInfoChanged?.Invoke(fingerprint, dna);
        RecordContainer.AddChild(newRecord);
    }

    private void FilterListingOfRecords(string text = "")
    {
        if (!_isPopulating)
            OnFiltersChanged?.Invoke(_currentFilterType, text);
    }

    private void UpdateRecordActionButtons()
    {
        if (_deleteConfirmationKey != _selectedKey)
            ResetDeleteConfirmation();

        AddRecordButton.Disabled = !_canManageRecords || string.IsNullOrWhiteSpace(StationRecordsFiltersValue.Text);
        DeleteRecordButton.Disabled = !_canManageRecords || _selectedKey == null;
        DeleteRecordButton.ToolTip = _deleteConfirmationPending ? "confirm delete" : "delete";

        if (_deleteConfirmationPending)
        {
            if (!DeleteRecordButton.StyleClasses.Contains("ButtonColorRed"))
                DeleteRecordButton.StyleClasses.Add("ButtonColorRed");
        }
        else
        {
            DeleteRecordButton.StyleClasses.Remove("ButtonColorRed");
        }
    }

    private void CreateRecordFromSearch()
    {
        var name = StationRecordsFiltersValue.Text.Trim();
        if (name.Length == 0)
            return;

        ResetDeleteConfirmation();
        OnCreateRecord?.Invoke(name);
    }

    private void ResetDeleteConfirmation()
    {
        _deleteConfirmationPending = false;
        _deleteConfirmationKey = null;
    }

    private string GetTypeFilterLocals(StationRecordFilterType type)
    {
        return Loc.GetString($"general-station-record-{type.ToString().ToLower()}-filter");
    }
}
