// SPDX-FileCopyrightText: 2025 GoobBot <uristmchands@proton.me>
// SPDX-FileCopyrightText: 2025 Roudenn <romabond091@gmail.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

// Copyright Rane (elijahrane@gmail.com) 2025
// All rights reserved. Relicensed under AGPL with permission

using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared._Mono.FireControl;
using Content.Shared._Mono.ShipGuns;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.Controls;

namespace Content.Client._Mono.FireControl.UI;

[GenerateTypedNameReferences]
public sealed partial class FireControlWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entityManager = default!;

    public FireControlNavControl Radar => NavRadar;
    public Action? OnServerRefresh;
    public Action? OnWeaponSelectionChanged;
    public Action<int>? OnLayerSelected; // Pirate: multiz

    public readonly Dictionary<NetEntity, Button> WeaponsList = new();

    // Dictionary to store weapon name to entity mapping for easier filtering
    private readonly Dictionary<string, NetEntity> _weaponNameToEntity = new();

    // Dictionary to store weapon entity to type mapping
    private readonly Dictionary<NetEntity, ShipGunType> _weaponTypes = new();

    #region Pirate: multiz
    /// <summary>
    /// Per-gun metadata kept on the client so the disable/deselect pass can run against the
    /// current layer without bouncing off the server every time the operator toggles a layer.
    /// </summary>
    private readonly Dictionary<NetEntity, (int Depth, int Reach)> _weaponLayerInfo = new();

    private int _currentLayerDepth;
    #endregion Pirate: multiz

    public FireControlWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        RefreshButton.OnPressed += _ => OnServerRefresh?.Invoke();
        SelectAllButton.OnPressed += SelectAllWeapons;
        UnselectAllButton.OnPressed += UnselectAllWeapons;
        SelectBallisticButton.OnPressed += SelectBallisticWeapons;
        SelectEnergyButton.OnPressed += SelectEnergyWeapons;
        SelectMissileButton.OnPressed += SelectMissileWeapons;
        SelectMiningButton.OnPressed += SelectMiningWeapons; //Lua Addition
    }

    private void SelectAllWeapons(BaseButton.ButtonEventArgs args)
    {
        foreach (var button in WeaponsList.Values)
        {
            if (button.Disabled) // Pirate: multiz — don't toggle unreachable guns on
                continue;
            button.Pressed = true;
        }

        OnWeaponSelectionChanged?.Invoke();
    }

    private void UnselectAllWeapons(BaseButton.ButtonEventArgs args)
    {
        foreach (var button in WeaponsList.Values)
        {
            button.Pressed = false;
        }

        OnWeaponSelectionChanged?.Invoke();
    }

    private void SelectBallisticWeapons(BaseButton.ButtonEventArgs args)
    {
        // First unselect all weapons
        foreach (var button in WeaponsList.Values)
        {
            button.Pressed = false;
        }

        // Then select only ballistic weapons
        foreach (var kvp in WeaponsList)
        {
            var weaponEntity = kvp.Key;
            var button = kvp.Value;

            if (_weaponTypes.TryGetValue(weaponEntity, out var type) && type == ShipGunType.Ballistic && !button.Disabled) // Pirate: multiz
            {
                button.Pressed = true;
            }
        }

        OnWeaponSelectionChanged?.Invoke();
    }

    private void SelectEnergyWeapons(BaseButton.ButtonEventArgs args)
    {
        // First unselect all weapons
        foreach (var button in WeaponsList.Values)
        {
            button.Pressed = false;
        }

        // Then select only energy weapons
        foreach (var kvp in WeaponsList)
        {
            var weaponEntity = kvp.Key;
            var button = kvp.Value;

            if (_weaponTypes.TryGetValue(weaponEntity, out var type) && type == ShipGunType.Energy && !button.Disabled) // Pirate: multiz
            {
                button.Pressed = true;
            }
        }

        OnWeaponSelectionChanged?.Invoke();
    }

    private void SelectMissileWeapons(BaseButton.ButtonEventArgs args)
    {
        // First unselect all weapons
        foreach (var button in WeaponsList.Values)
        {
            button.Pressed = false;
        }

        // Then select only missile weapons
        foreach (var kvp in WeaponsList)
        {
            var weaponEntity = kvp.Key;
            var button = kvp.Value;

            if (_weaponTypes.TryGetValue(weaponEntity, out var type) && type == ShipGunType.Missile && !button.Disabled) // Pirate: multiz
            {
                button.Pressed = true;
            }
        }

        OnWeaponSelectionChanged?.Invoke();
    }

    //Lua Addition start
    private void SelectMiningWeapons(BaseButton.ButtonEventArgs args)
    {
        // First unselect all weapons
        foreach (var button in WeaponsList.Values)
        {
            button.Pressed = false;
        }

        // Then select only mining weapons
        foreach (var kvp in WeaponsList)
        {
            var weaponEntity = kvp.Key;
            var button = kvp.Value;

            if (_weaponTypes.TryGetValue(weaponEntity, out var type) && type == ShipGunType.Mining && !button.Disabled) // Pirate: multiz
            {
                button.Pressed = true;
            }
        }

        OnWeaponSelectionChanged?.Invoke();
    }
    //Lua Addition end

    public void UpdateStatus(FireControlConsoleBoundInterfaceState state)
    {
        NavRadar.UpdateState(state.NavState);

        if (state.Connected)
        {
            ServerStatus.Text = Loc.GetString("gunnery-window-connected");
            ServerStatus.FontColorOverride = Color.Green;
        }
        else
        {
            RefreshButton.Disabled = false;
            ServerStatus.Text = Loc.GetString("gunnery-window-disconnected");
            ServerStatus.FontColorOverride = Color.Red;
        }

        #region Pirate: multiz
        _currentLayerDepth = state.CurrentLayer;
        RebuildLayerSelector(state);
        #endregion Pirate: multiz

        UpdateWeaponsList(state);
        // Pirate: multiz — ApplyLayerReachability (run from UpdateWeaponsList) handles both the
        // per-gun disable state and the category-button enable state, with reachability taken
        // into account. The old "are any of this type present?" pass that lived here has been
        // folded into that method so they can't fight each other.
    }

    private void UpdateWeaponsList(FireControlConsoleBoundInterfaceState state)
    {
        if (state.FireControllables == null)
        {
            WeaponsList.Clear();
            ControllablesBox.DisposeAllChildren();
            _weaponNameToEntity.Clear();
            _weaponTypes.Clear();
            _weaponLayerInfo.Clear(); // Pirate: multiz
            return;
        }

        var toRemove = new HashSet<NetEntity>(WeaponsList.Keys);
        _weaponNameToEntity.Clear();
        _weaponTypes.Clear();
        _weaponLayerInfo.Clear(); // Pirate: multiz

        foreach (var controllable in state.FireControllables)
        {
            // Store the weapon name and entity for filtering
            _weaponNameToEntity[controllable.Name] = controllable.NetEntity;
            _weaponLayerInfo[controllable.NetEntity] = (controllable.Depth, controllable.Reach); // Pirate: multiz

            // Store the weapon type if available
            var entity = _entityManager.GetEntity(controllable.NetEntity);
            if (_entityManager.TryGetComponent<ShipGunTypeComponent>(entity, out var typeComp))
            {
                _weaponTypes[controllable.NetEntity] = typeComp.Type;
            }

            if (WeaponsList.TryGetValue(controllable.NetEntity, out var existingButton))
            {
                toRemove.Remove(controllable.NetEntity);
            }
            else
            {
                var button = new Button
                {
                    ToggleMode = true,
                    Text = controllable.Name,
                    StyleClasses = { "ButtonSquare OpenRight" },
                    HorizontalExpand = true,
                    Margin = new Thickness(4, 1)
                };

                button.OnToggled += _ => OnWeaponSelectionChanged?.Invoke();

                ControllablesBox.AddChild(button);
                WeaponsList.Add(controllable.NetEntity, button);
            }
        }

        foreach (var entity in toRemove)
        {
            if (WeaponsList.TryGetValue(entity, out var button))
            {
                ControllablesBox.RemoveChild(button);
                WeaponsList.Remove(entity);
            }
        }

        SelectAllButton.Disabled = WeaponsList.Count == 0;
        UnselectAllButton.Disabled = WeaponsList.Count == 0;

        ApplyLayerReachability(); // Pirate: multiz
    }

    #region Pirate: multiz
    /// <summary>
    /// Rebuilds the layer-selector strip from the BUI state. Hidden when only one layer is
    /// available so single-deck shuttles see no UI change.
    /// </summary>
    private void RebuildLayerSelector(FireControlConsoleBoundInterfaceState state)
    {
        LayerSelectorRow.RemoveAllChildren();

        if (state.Layers.Length <= 1)
        {
            LayerSelectorRow.Visible = false;
            return;
        }

        LayerSelectorRow.Visible = true;

        var group = new ButtonGroup();
        foreach (var layer in state.Layers)
        {
            var pressed = layer.Depth == state.CurrentLayer;
            var button = new Button
            {
                Text = layer.Depth.ToString(),
                ToggleMode = true,
                Group = group,
                Pressed = pressed,
                Margin = new Thickness(2f, 0f),
                MinSize = new Vector2(28f, 0f),
            };

            var capturedDepth = layer.Depth;
            button.OnPressed += _ =>
            {
                if (capturedDepth == _currentLayerDepth)
                    return;
                OnLayerSelected?.Invoke(capturedDepth);
            };

            LayerSelectorRow.AddChild(button);
        }
    }

    /// <summary>
    /// Greys out and deselects every gun whose own depth is too far from the current layer to
    /// reach it. Runs after the gun list is rebuilt and again whenever the layer changes.
    /// </summary>
    private void ApplyLayerReachability()
    {
        var anyChanged = false;

        foreach (var (netEntity, button) in WeaponsList)
        {
            var reachable = true;
            if (_weaponLayerInfo.TryGetValue(netEntity, out var info))
                reachable = Math.Abs(info.Depth - _currentLayerDepth) <= info.Reach;

            button.Disabled = !reachable;
            if (!reachable && button.Pressed)
            {
                button.Pressed = false;
                anyChanged = true;
            }
        }

        // Category-quick-select buttons should also reflect whether any reachable gun exists.
        var hasBallistic = false;
        var hasEnergy = false;
        var hasMissile = false;
        var hasMining = false;
        foreach (var (netEntity, type) in _weaponTypes)
        {
            if (!WeaponsList.TryGetValue(netEntity, out var button) || button.Disabled)
                continue;
            switch (type)
            {
                case ShipGunType.Ballistic: hasBallistic = true; break;
                case ShipGunType.Energy: hasEnergy = true; break;
                case ShipGunType.Missile: hasMissile = true; break;
                case ShipGunType.Mining: hasMining = true; break;
            }
        }

        SelectBallisticButton.Disabled = !hasBallistic;
        SelectEnergyButton.Disabled = !hasEnergy;
        SelectMissileButton.Disabled = !hasMissile;
        SelectMiningButton.Disabled = !hasMining;

        if (anyChanged)
            OnWeaponSelectionChanged?.Invoke();
    }
    #endregion Pirate: multiz
}
