// SPDX-FileCopyrightText: 2025 ark1368
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Robust.Shared.Audio;

namespace Content.Shared._Pirate.ShipShields;

[RegisterComponent]
public sealed partial class ShipShieldEmitterComponent : Component
{
    /// <summary>
    /// All shield bubbles this emitter currently owns, keyed by the grid each one protects.
    /// A z-linked emitter shields every peer grid in its <c>CEZLinkedGridComponent</c> network,
    /// so this is a 1:N map even though a single grid only ever has one entry.
    /// </summary>
    public Dictionary<EntityUid, EntityUid> Shields = new();

    /// <summary>
    /// True while the emitter is producing shields (i.e. <see cref="Shields"/> is non-empty
    /// or should be). Used to gate the per-tick reconciliation pass.
    /// </summary>
    public bool Active;

    [DataField]
    public float Accumulator;

    [DataField]
    public float Damage = 0f;

    [DataField]
    public float DamageExp = 1.1f;

    [DataField]
    public float HealPerSecond = 250f;

    [DataField]
    public float UnpoweredBonus = 6f;

    [DataField]
    public float MaxDraw = 150000f;

    [DataField]
    public float BaseDraw = 50000f;

    [DataField]
    public bool Recharging = false;

    [DataField]
    public float DamageLimit = 3500;

    [DataField]
    public float DamageOverloadTimePunishment = 30;

    /// <summary>
    /// The color of the shield generated by this emitter.
    /// </summary>
    [DataField]
    public Color ShieldColor = Color.White;

    public float OverloadAccumulator = 0f;

    /// <summary>
    /// The grid in the current shielded peer set whose AABB is being used as the shape
    /// template for every shield bubble this emitter owns. Stored so we can detect when the
    /// largest grid in the network changes and re-spawn all bubbles to keep them visually
    /// uniform across z-layers.
    /// </summary>
    public EntityUid? TemplateGrid;

    /// <summary>
    /// On power up, players for all on vessel, pitched down.
    /// </summary>
    [DataField]
    public SoundSpecifier PowerUpSound = new SoundPathSpecifier("/Audio/Effects/teleport_arrival.ogg");

    [DataField]
    public SoundSpecifier PowerDownSound = new SoundPathSpecifier("/Audio/Effects/teleport_departure.ogg");
}
