// SPDX-FileCopyrightText: 2026 Corvax Team Contributors
// SPDX-FileCopyrightText: 2026 CyberLanos <cyber.lanos00@gmail.com>
//
// SPDX-License-Identifier: AGPL-3.0-only

using Robust.Client.Audio;
using Robust.Client.AutoGenerated;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Audio.Sources;
using Robust.Shared.Utility;
using System.Numerics;

namespace Content.Client._Pirate.Photo.UI;

[GenerateTypedNameReferences]
public sealed partial class TextureButton : ContainerButton
{
    [Dependency] private readonly IAudioManager _audioManager = default!;

    public TextureButton()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Icon.DisplayRect.Stretch = TextureRect.StretchMode.Scale;

        this.OnMouseEntered += args =>
        {
            if (PointedTexture != null)
                Icon.SetFromSpriteSpecifier(PointedTexture);
        };

        this.OnMouseExited += args =>
        {
            if (BaseTexture != null)
                Icon.SetFromSpriteSpecifier(BaseTexture);
        };

        this.OnButtonDown += args =>
        {
            if (PressedTexture != null)
                Icon.SetFromSpriteSpecifier(PressedTexture);

            _clickSound?.Restart();
        };

        this.OnButtonUp += args =>
        {
            if (IsHovered && PointedTexture != null)
                Icon.SetFromSpriteSpecifier(PointedTexture);
            else
                RefreshTexture();
        };
    }

    public void ShowBase()
    {
        RefreshTexture();
    }

    public Vector2 TextureScale
    {
        get => Icon.DisplayRect.SetSize;
        set => Icon.DisplayRect.SetSize = value;
    }

    public SpriteSpecifier? BaseTexture
    {
        get => _baseTexture;
        set
        {
            _baseTexture = value;
            RefreshTexture();
        }
    }
    public SpriteSpecifier? PointedTexture { get; set; }
    public SpriteSpecifier? PressedTexture { get; set; }

    public AudioResource? ClickSound
    {
        set
        {
            if (_clickSound != null)
            {
                _clickSound.Dispose();
                _clickSound = null;
            }

            if (value == null)
                return;

            var source = _audioManager.CreateAudioSource(value);
            if (source == null)
                return;

            source.Global = true;
            _clickSound = source;
        }
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);
        _clickSound?.Dispose();
        _clickSound = null;
    }

    private IAudioSource? _clickSound;
    private SpriteSpecifier? _baseTexture;

    private void RefreshTexture()
    {
        if (BaseTexture != null)
            Icon.SetFromSpriteSpecifier(BaseTexture);
    }
}


